# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: sshimizu <sshimizu@student.42tokyo.jp>     +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2023/07/07 16:58:32 by sshimizu          #+#    #+#              #
#    Updated: 2023/07/07 17:04:45 by sshimizu         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = phonebook

all: $(NAME)

$(NAME): main.cpp PhoneBook.cpp PhoneBook.hpp Contact.cpp Contact.hpp
	c++ -std=c++98 $^
